<?xml version="1.0" ?>
<robot name="book_part" 
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller" 
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface" 
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor" 
       xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- 
       basic ROS xacro macro for a "book": a cube with textures.

       Origin is at z=0 and at back-spine edge (because that
       is where the axis for turning pages is connected to the 
       next part of the book).

       Center of mass are at the center of the mesh.

       (C) 2019 fnh, hendrich@informatik.uni-hamburg.de
  -->

<xacro:macro name="book_part" params="name weight mesh xsize ysize zsize">

  <!-- main body with Collada mesh for both visual and collision -->
  <link name="${name}_link">
    <inertial>
      <mass value="${weight}"/>
      <origin rpy="0 0 0" xyz="${xsize/2} ${-ysize/2} 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
    <collision>
      <origin rpy="0 0 0" xyz="${xsize/2} ${-ysize/2} 0"/>
      <geometry>
        <box size="${xsize} ${ysize} ${zsize}" rpy="0 0 0" />
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="${xsize/2} ${-ysize/2} 0"/>
      <geometry>
        <mesh filename="package://tams_books_world/meshes/${mesh}" scale="${0.5*xsize} ${0.5*ysize} ${0.5*zsize}" />
      </geometry>
    </visual>
  </link>
  <gazebo reference="${name}_link">
    <!-- material/texture definition for Gazebo -->
    <!-- <material>Gazebo/White</material> -->
    <turnGravityOff>false</turnGravityOff>
    <selfCollide>true</selfCollide>
    <mu1>10</mu1>
    <mu2>20</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>
</xacro:macro>

</robot>

